; PlatformIO Project Configuration File — cardputer-atari800
; https://docs.platformio.org/page/projectconf.html

[env:cardputer-adv]
platform = espressif32
framework = arduino
board = m5stack-cardputer

; serial / USB
monitor_speed = 115200
upload_speed = 921600

; C / C++ standards
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=3

; libraries — only bring in M5Cardputer for now; atari800 core added in M2
lib_deps =
  m5stack/M5Cardputer@^1.0.3

; flash / filesystem
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
