#pragma once
#include <stdint.h>

namespace audio_out {
  /* call EARLY in setup() — before M5Cardputer.begin() — so the buffer
     malloc lands in the big-contiguous-block heap window. Returns false
     if alloc fails. */
  bool preallocate_buffers();

  /* Call AFTER M5Cardputer.begin() AND Atari800_Initialise(). Configures
     I2S driver, sample rate, stereo output slots, and ES8311 registers.
     Audio samples are generated by the lightweight register-driven POKEY
     synth in the I2S task so the emulator frame path stays responsive. */
  bool start(int initial_stereo);

  /* Mute/unmute by setting Speaker volume to 0 / previous. */
  void set_muted(bool muted);

  /* Runtime stereo toggle — reinits POKEY engine. Cheap (~1 ms). */
  void set_stereo(bool stereo);

  /* Drop fast POKEY output for a short startup/reset window. */
  void suppress_for_ms(uint32_t ms);

  /* Volume delta, signed (+ or -). Clamps to [0, 255]. */
  void set_volume_delta(int8_t delta);

  /* Called once per atari frame from the weak Sound_Update override.
     Audio is streamed by a background task, so this is intentionally cheap. */
  void pump();
}
